export enum ClienteError {
    NO_ENCONTRADO = 'CLNT_000',
    INTEGRIDAD_VIOLADA = 'CLNT_001',
    REQUERIDO = 'CLNT_002',
    DUPLICADO = 'CLNT_003',
    CONTRASENA_REQUERIDO = 'CLNT_004',
    CORREO_DUPLICADO = 'CLNT_005',
    CORREO_REQUERIDO = 'CLNT_006',
    CORREO_NO_ENCONTRADO = 'CLNT_007',
    ID_REQUERIDO = 'CLNT_008',
    ID_INVALIDO = 'CLNT_009'
}
