export enum EmpleadoError {
    NO_ENCONTRADO = 'EMPL_000',
    INTEGRIDAD_VIOLADA = 'EMPL_001',
    REQUERIDO = 'EMPL_002',
    DUPLICADO = 'EMPL_003',
    CONTRASENA_REQUERIDO = 'EMPL_004',
    CORREO_DUPLICADO = 'EMPL_005',
    CORREO_REQUERIDO = 'EMPL_006',
    CORREO_NO_ENCONTRADO = 'EMPL_007',
    ID_REQUERIDO = 'EMPL_008',
    ID_INVALIDO = 'EMPL_009'
}
